# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f_s_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_f_s_dialog(object):
    def setupUi(self, f_s_dialog):
        f_s_dialog.setObjectName("f_s_dialog")
        f_s_dialog.resize(435, 562)
        font = QtGui.QFont()
        font.setPointSize(11)
        f_s_dialog.setFont(font)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(f_s_dialog)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(f_s_dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.year = QtWidgets.QDateEdit(f_s_dialog)
        self.year.setObjectName("year")
        self.horizontalLayout.addWidget(self.year)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(f_s_dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.months = QtWidgets.QScrollArea(f_s_dialog)
        self.months.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.months.setFrameShadow(QtWidgets.QFrame.Plain)
        self.months.setWidgetResizable(True)
        self.months.setObjectName("months")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 310, 455))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.months.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.months)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cancel = QtWidgets.QPushButton(f_s_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel.sizePolicy().hasHeightForWidth())
        self.cancel.setSizePolicy(sizePolicy)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_3.addWidget(self.cancel)
        self.confirm = QtWidgets.QPushButton(f_s_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirm.sizePolicy().hasHeightForWidth())
        self.confirm.setSizePolicy(sizePolicy)
        self.confirm.setObjectName("confirm")
        self.horizontalLayout_3.addWidget(self.confirm)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.setStretch(0, 9)
        self.verticalLayout_3.setStretch(1, 1)

        self.retranslateUi(f_s_dialog)
        QtCore.QMetaObject.connectSlotsByName(f_s_dialog)

    def retranslateUi(self, f_s_dialog):
        _translate = QtCore.QCoreApplication.translate
        f_s_dialog.setWindowTitle(_translate("f_s_dialog", "财务统计"))
        self.label.setText(_translate("f_s_dialog", "年份"))
        self.year.setDisplayFormat(_translate("f_s_dialog", "yyyy"))
        self.label_2.setText(_translate("f_s_dialog", "月份"))
        self.cancel.setText(_translate("f_s_dialog", "取消"))
        self.confirm.setText(_translate("f_s_dialog", "确认"))
