# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'custom_tool_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_custom_tool_box(object):
    def setupUi(self, custom_tool_box):
        custom_tool_box.setObjectName("custom_tool_box")
        custom_tool_box.resize(363, 488)
        font = QtGui.QFont()
        font.setPointSize(11)
        custom_tool_box.setFont(font)
        custom_tool_box.setMouseTracking(True)
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 363, 430))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.page.setFont(font)
        self.page.setObjectName("page")
        self.layoutWidget = QtWidgets.QWidget(self.page)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 361, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.font_color = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.font_color.sizePolicy().hasHeightForWidth())
        self.font_color.setSizePolicy(sizePolicy)
        self.font_color.setObjectName("font_color")
        self.horizontalLayout.addWidget(self.font_color)
        self.fill_color = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fill_color.sizePolicy().hasHeightForWidth())
        self.fill_color.setSizePolicy(sizePolicy)
        self.fill_color.setObjectName("fill_color")
        self.horizontalLayout.addWidget(self.fill_color)
        custom_tool_box.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 363, 430))
        self.page_2.setObjectName("page_2")
        custom_tool_box.addItem(self.page_2, "")

        self.retranslateUi(custom_tool_box)
        QtCore.QMetaObject.connectSlotsByName(custom_tool_box)

    def retranslateUi(self, custom_tool_box):
        _translate = QtCore.QCoreApplication.translate
        custom_tool_box.setWindowTitle(_translate("custom_tool_box", "功能区"))
        self.page.setWindowTitle(_translate("custom_tool_box", "功能区"))
        self.font_color.setText(_translate("custom_tool_box", "字体颜色"))
        self.fill_color.setText(_translate("custom_tool_box", "背景颜色"))
        custom_tool_box.setItemText(custom_tool_box.indexOf(self.page), _translate("custom_tool_box", "颜色"))
        custom_tool_box.setItemText(custom_tool_box.indexOf(self.page_2), _translate("custom_tool_box", "其他"))
